---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stress-test
spec:
  replicas: 3
  template:
    metadata: 
      labels:
        app: stress-test
    spec: 
      # affinity:
      #   nodeAffinity: 
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: kubernetes.io/hostname
      #           operator: In
      #           values:
      #           - #NODE
      volumes:
      - name: shared-data
        hostPath:
          path: /usr/share/nginx/html
      # - name: stress-test
      #   persistentVolumeClaim:
      #     claimName: insightsclaim
      containers:
      - name: stress
        image: polinux/stress
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
        command: ["stress"]
        args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]