apiVersion: v1
kind: Pod
metadata:
  name: stress-test
spec:
  volumes:
  - name: shared-data
    hostPath:
      path: /usr/share/nginx/html
  - name: stress-test
    persistentVolumeClaim:
      claimName: insightsclaim
  containers:
  - name: stress
    image: polinux/stress
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "250M", "--vm-hang", "1"]